#pragma once

typedef enum
{
    STATE_WAIT_SYNC_LOW,
    STATE_WAIT_SYNC_HIGH,
    STATE_WAIT_VERSION,
    STATE_WAIT_ID_LOW,
    STATE_WAIT_ID_HIGH,
    STATE_WAIT_SEQ_LOW,
    STATE_WAIT_SEQ_HIGH,
    STATE_WAIT_LEN_LOW,
    STATE_WAIT_LEN_HIGH,
    STATE_WAIT_PAYLOAD,
    STATE_WAIT_CRC_LOW,
    STATE_WAIT_CRC_HIGH
} RxState;